title: ML thoughts
author: https://github.com/sujoyde89
email: sujoy.powerju@gmail.com

github_username:  https://github.com/sujoyde89

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
  - about.html

# Build settings
markdown: kramdown
theme: 
exclude:
  - Gemfile
  - Gemfile.lock
  - History.markdown
